/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Cliente;

import controller.Concessionaria;
import model.Cliente;
import javax.swing.JOptionPane;
import view.MenuPrincipal;


/**
 *
 * @author hiago
 */
public class EditCliente extends javax.swing.JFrame {
    
    private final Concessionaria controller;
    private final RelatorioCliente relatorioCliente;
    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form FormularioCliente
     */
    public EditCliente(Concessionaria controller, RelatorioCliente relatorioCliente, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.relatorioCliente = relatorioCliente;
        this.menuPrincipal = menuPrincipal;
        
        alterar.setEnabled(false); 
        remover.setEnabled(false); 
    
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        cpfCliente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        rgCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numTelefone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        voltar.setBackground(new java.awt.Color(45, 60, 80));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(20, 353, 90, 30);

        relatorio.setBackground(new java.awt.Color(45, 60, 80));
        relatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorio.setForeground(new java.awt.Color(255, 255, 255));
        relatorio.setText("Relatório");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        jPanel1.add(relatorio);
        relatorio.setBounds(120, 353, 90, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar);
        limpar.setBounds(80, 140, 70, 30);

        remover.setBackground(new java.awt.Color(227, 6, 19));
        remover.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        remover.setForeground(new java.awt.Color(255, 255, 255));
        remover.setText("Remover");
        remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerActionPerformed(evt);
            }
        });
        jPanel1.add(remover);
        remover.setBounds(320, 290, 90, 30);

        alterar.setBackground(new java.awt.Color(108, 117, 125));
        alterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterar.setForeground(new java.awt.Color(255, 255, 255));
        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        jPanel1.add(alterar);
        alterar.setBounds(420, 290, 72, 30);

        consultar.setBackground(new java.awt.Color(0, 168, 89));
        consultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultar.setForeground(new java.awt.Color(255, 255, 255));
        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar);
        consultar.setBounds(160, 140, 90, 30);
        jPanel1.add(cpfCliente);
        cpfCliente.setBounds(80, 100, 170, 30);

        jLabel7.setForeground(new java.awt.Color(95, 118, 153));
        jLabel7.setText("CPF");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 80, 160, 16);
        jPanel1.add(rgCliente);
        rgCliente.setBounds(300, 200, 220, 30);

        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("RG");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 180, 140, 16);
        jPanel1.add(emailCliente);
        emailCliente.setBounds(300, 150, 220, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 130, 220, 16);
        jPanel1.add(numTelefone);
        numTelefone.setBounds(300, 250, 220, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("Número de Telefone");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 230, 230, 16);

        jLabel3.setForeground(new java.awt.Color(95, 118, 153));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 80, 200, 16);
        jPanel1.add(nomeCliente);
        nomeCliente.setBounds(300, 100, 220, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Clientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        // TODO add your handling code here:
        String cpfBusca = cpfCliente.getText(); 

        if (cpfBusca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite um CPF para buscar.");
            return;
        }

        Cliente cliente = this.controller.consultarCliente(cpfBusca);

        if (cliente != null) {
            nomeCliente.setText(cliente.getNome());
            numTelefone.setText(cliente.getNumTelefone());
            emailCliente.setText(cliente.getEmailPessoal());
            rgCliente.setText(cliente.getRg());
            cpfCliente.setEditable(false); 
            rgCliente.setEditable(false);
            
            alterar.setEnabled(true);  
            remover.setEnabled(true); 
            
        } else {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado.");
            limparActionPerformed(evt);
        }
    }//GEN-LAST:event_consultarActionPerformed

    private void removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerActionPerformed
        // TODO add your handling code here:
        String cpf = cpfCliente.getText();
        
        if (cpf.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite o CPF para remover.");
            return;
            }
    
        this.controller.removerCliente(cpf);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente removido com sucesso!");
        limparActionPerformed(evt);  
    }//GEN-LAST:event_removerActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        String cpf = cpfCliente.getText(); 
        String novoNome = nomeCliente.getText();
        String novoTelefone = numTelefone.getText();
        String novoEmail = emailCliente.getText();
        rgCliente.getText();

        if (cpf.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Consulte um cliente antes de alterar.");
            return;
        }

        this.controller.alterarCliente(novoNome, novoTelefone, novoEmail, cpf);
    
        javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
        limparActionPerformed(evt);
    }//GEN-LAST:event_alterarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        nomeCliente.setText("");
        numTelefone.setText("");
        emailCliente.setText("");
        rgCliente.setText("");
        cpfCliente.setText("");
    
        cpfCliente.setEditable(true);
        
       alterar.setEnabled(false);   
       remover.setEnabled(false);   
       
    }//GEN-LAST:event_limparActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        this.relatorioCliente.setVisible(true);
    }//GEN-LAST:event_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton consultar;
    private javax.swing.JTextField cpfCliente;
    private javax.swing.JTextField emailCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JTextField numTelefone;
    private javax.swing.JButton relatorio;
    private javax.swing.JButton remover;
    private javax.swing.JTextField rgCliente;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
