/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Veiculo;

import controller.Concessionaria;
import model.Veiculo;
import javax.swing.JOptionPane;
import view.MenuPrincipal;
/**
 *
 * @author hiago
 */
public class EditVeiculo extends javax.swing.JFrame {
    
    private final Concessionaria controller;
    private final RelatorioVeiculo relatorioVeiculo;
    private MenuPrincipal menuPrincipal;

    /**
     * Creates new form FormularioVeiculo
     */
    public EditVeiculo(Concessionaria controller, RelatorioVeiculo relatorioVeiculo, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.relatorioVeiculo = relatorioVeiculo;
        this.menuPrincipal = menuPrincipal;
        
        alterarVeiculo.setEnabled(false);
        removerVeiculo.setEnabled(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        consultarVeiculo = new javax.swing.JButton();
        removerVeiculo = new javax.swing.JButton();
        alterarVeiculo = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numMarchas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numPortas = new javax.swing.JTextField();
        Marca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anoFabricacao = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Veículos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 43);

        consultarVeiculo.setBackground(new java.awt.Color(0, 168, 89));
        consultarVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        consultarVeiculo.setText("Consultar");
        consultarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(consultarVeiculo);
        consultarVeiculo.setBounds(161, 140, 90, 30);

        removerVeiculo.setBackground(new java.awt.Color(227, 6, 19));
        removerVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removerVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        removerVeiculo.setText("Remover");
        removerVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(removerVeiculo);
        removerVeiculo.setBounds(330, 340, 80, 30);

        alterarVeiculo.setBackground(new java.awt.Color(108, 117, 125));
        alterarVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        alterarVeiculo.setText("Alterar");
        alterarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(alterarVeiculo);
        alterarVeiculo.setBounds(420, 340, 72, 30);

        voltar.setBackground(new java.awt.Color(45, 60, 80));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(20, 350, 90, 30);

        jLabel3.setForeground(new java.awt.Color(95, 118, 153));
        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(310, 80, 42, 16);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome);
        nome.setBounds(310, 100, 210, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Cor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 130, 37, 16);
        jPanel1.add(cor);
        cor.setBounds(310, 150, 210, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Número de marchas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(310, 180, 107, 16);
        jPanel1.add(numMarchas);
        numMarchas.setBounds(310, 200, 110, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("Número de portas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(430, 180, 107, 16);
        jPanel1.add(numPortas);
        numPortas.setBounds(430, 200, 90, 30);

        Marca.setForeground(new java.awt.Color(95, 118, 153));
        Marca.setText("Marca");
        jPanel1.add(Marca);
        Marca.setBounds(310, 230, 37, 16);
        jPanel1.add(marca);
        marca.setBounds(310, 250, 210, 30);

        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("Ano de fabricação");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(310, 280, 98, 16);
        jPanel1.add(anoFabricacao);
        anoFabricacao.setBounds(310, 300, 210, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setLabel("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar);
        limpar.setBounds(80, 140, 72, 30);

        relatorio.setBackground(new java.awt.Color(45, 60, 80));
        relatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorio.setForeground(new java.awt.Color(255, 255, 255));
        relatorio.setText("Relatório");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        jPanel1.add(relatorio);
        relatorio.setBounds(120, 350, 90, 30);

        jLabel7.setForeground(new java.awt.Color(95, 118, 153));
        jLabel7.setText("ID");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 80, 37, 16);
        jPanel1.add(id);
        id.setBounds(80, 100, 170, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVeiculoActionPerformed
        // TODO add your handling code here:      
        try {
            int idBusca = Integer.parseInt(id.getText());
        
            if (idBusca <= 0) {
                JOptionPane.showMessageDialog(this, "Digite um ID para buscar.");
                return;
            }

            Veiculo veiculo = this.controller.consultarVeiculo(idBusca);

            if (veiculo != null) {
                nome.setText(veiculo.getNome());
                cor.setText(veiculo.getCor());
                numMarchas.setText(String.valueOf(veiculo.getNumMarchas())); 
                numPortas.setText(String.valueOf(veiculo.getNumPortas()));   
                marca.setText(veiculo.getMarca());
                anoFabricacao.setText(veiculo.getAnoFabricacao());

                alterarVeiculo.setEnabled(true);
                removerVeiculo.setEnabled(true);
                id.setEditable(false); 
            } else {
                JOptionPane.showMessageDialog(this, "Veículo não encontrado.");
                limparActionPerformed(evt);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O ID deve ser numérico!");
        }   
    }//GEN-LAST:event_consultarVeiculoActionPerformed

    private void removerVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerVeiculoActionPerformed
        // TODO add your handling code here:
        try{
            int idVeiculo = Integer.parseInt(id.getText());
            
            if (idVeiculo <= 0) {
                JOptionPane.showMessageDialog(this, "Digite um ID válido (maior que 0).");
                return;
            }

            this.controller.removerVeiculo(idVeiculo);
            javax.swing.JOptionPane.showMessageDialog(this, "Veículo removido com sucesso!");
            limparActionPerformed(evt); 
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "O ID deve ser um número.");
        }
    }//GEN-LAST:event_removerVeiculoActionPerformed

    private void alterarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarVeiculoActionPerformed
        // TODO add your handling code here:
        try{
            int novoId = Integer.parseInt(id.getText());
            String novoNome = nome.getText();
            String novaCor = cor.getText();
            int novoNumMarchas = Integer.parseInt(numMarchas.getText());
            int novoNumPortas = Integer.parseInt(numPortas.getText());
            String novaMarca = marca.getText();
            String novoAnoFabricacao = anoFabricacao.getText();
        
            if (novoNome.isEmpty()) {
                return;
            }

            this.controller.alterarVeiculo(novoId, novoNome, novaCor, novoNumMarchas, novoNumPortas, novaMarca, novoAnoFabricacao);
    
            javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            limparActionPerformed(evt);
            
        } catch (NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: Id, Número de marchas e Número de portas devem ser números válidos.");
        }
    }//GEN-LAST:event_alterarVeiculoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        this.relatorioVeiculo.setVisible(true);
    }//GEN-LAST:event_relatorioActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        id.setText("");
        nome.setText("");
        cor.setText("");
        numMarchas.setText("");
        numPortas.setText("");
        marca.setText("");
        anoFabricacao.setText("");
    
        id.setEditable(true);
        alterarVeiculo.setEnabled(false);
        removerVeiculo.setEnabled(false);
    }//GEN-LAST:event_limparActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Marca;
    private javax.swing.JButton alterarVeiculo;
    private javax.swing.JTextField anoFabricacao;
    private javax.swing.JButton consultarVeiculo;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numMarchas;
    private javax.swing.JTextField numPortas;
    private javax.swing.JButton relatorio;
    private javax.swing.JButton removerVeiculo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
