/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Venda;

import controller.Concessionaria;
import model.Venda;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;
import model.Veiculo;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */
public class EditVenda extends javax.swing.JFrame {

    private final Concessionaria controller;
    private final RelatorioVenda relatorioVenda;
    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form FormularioVenda
     */
    public EditVenda(Concessionaria controller, RelatorioVenda relatorioVenda, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.relatorioVenda = relatorioVenda;
        this.menuPrincipal = menuPrincipal;
        
        alterarVenda.setEnabled(false);
        removerVenda.setEnabled(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        removerVenda = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        veiculo = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        alterarVenda = new javax.swing.JButton();
        consultarVenda = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(519, 191, 0, 0);

        jPanel2.setBackground(new java.awt.Color(18, 18, 18));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Vendas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 43);

        removerVenda.setBackground(new java.awt.Color(227, 6, 19));
        removerVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removerVenda.setForeground(new java.awt.Color(255, 255, 255));
        removerVenda.setText("Remover");
        removerVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerVendaActionPerformed(evt);
            }
        });
        jPanel2.add(removerVenda);
        removerVenda.setBounds(330, 340, 80, 30);

        voltar.setBackground(new java.awt.Color(45, 60, 80));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel2.add(voltar);
        voltar.setBounds(20, 350, 90, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Data");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 80, 37, 16);
        jPanel2.add(data);
        data.setBounds(310, 100, 210, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Valor");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(310, 280, 37, 16);
        jPanel2.add(valor);
        valor.setBounds(310, 300, 210, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("CPF Cliente");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(310, 130, 59, 16);
        jPanel2.add(cliente);
        cliente.setBounds(310, 150, 210, 30);

        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("ID Funcionário");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(310, 180, 100, 16);
        jPanel2.add(funcionario);
        funcionario.setBounds(310, 200, 210, 30);

        jLabel7.setForeground(new java.awt.Color(95, 118, 153));
        jLabel7.setText("ID Veículo");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(310, 230, 54, 16);
        jPanel2.add(veiculo);
        veiculo.setBounds(310, 250, 210, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel2.add(limpar);
        limpar.setBounds(80, 140, 72, 30);

        relatorio.setBackground(new java.awt.Color(45, 60, 80));
        relatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorio.setForeground(new java.awt.Color(255, 255, 255));
        relatorio.setText("Relatório");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        jPanel2.add(relatorio);
        relatorio.setBounds(120, 350, 90, 30);

        alterarVenda.setBackground(new java.awt.Color(108, 117, 125));
        alterarVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarVenda.setForeground(new java.awt.Color(255, 255, 255));
        alterarVenda.setText("Alterar");
        alterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarVendaActionPerformed(evt);
            }
        });
        jPanel2.add(alterarVenda);
        alterarVenda.setBounds(420, 340, 72, 30);

        consultarVenda.setBackground(new java.awt.Color(0, 168, 89));
        consultarVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultarVenda.setForeground(new java.awt.Color(255, 255, 255));
        consultarVenda.setText("Consultar");
        consultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVendaActionPerformed(evt);
            }
        });
        jPanel2.add(consultarVenda);
        consultarVenda.setBounds(161, 140, 90, 30);

        jLabel8.setForeground(new java.awt.Color(95, 118, 153));
        jLabel8.setText("ID");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(80, 80, 37, 16);
        jPanel2.add(id);
        id.setBounds(80, 100, 170, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVendaActionPerformed
        // TODO add your handling code here:
        int idBusca = Integer.parseInt(id.getText());
        
        if (idBusca == 0) {
            JOptionPane.showMessageDialog(this, "Digite um id para bsucar.");
            return;
        }
        
        Venda venda = this.controller.consultarVenda(idBusca);
        
        if (venda != null) {
            id.setText(String.valueOf(venda.getId()));
            data.setText(venda.getData());
            valor.setText(String.valueOf(venda.getValor()));
            cliente.setText(venda.getCliente().getCpf());
            funcionario.setText(String.valueOf(venda.getFuncionario().getNumMatricula()));
            veiculo.setText(String.valueOf(venda.getVeiculo().getId()));
            
            alterarVenda.setEnabled(true);  
            removerVenda.setEnabled(true); 
        } else {
            JOptionPane.showMessageDialog(this, "Venda não encontrada.");
            limparActionPerformed(evt);
        }
    }//GEN-LAST:event_consultarVendaActionPerformed

    private void removerVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerVendaActionPerformed
        // TODO add your handling code here:
        int idVenda = Integer.parseInt(id.getText());
        
        if (idVenda == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite o id para remover.");
            return;
            }
        
        this.controller.removerVenda(idVenda);
        
        javax.swing.JOptionPane.showMessageDialog(this, "Venda removida com sucesso!");
        limparActionPerformed(evt);
    }//GEN-LAST:event_removerVendaActionPerformed

    private void alterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarVendaActionPerformed
        // TODO add your handling code here:
        int novoId = Integer.parseInt(id.getText());
        String novaData = data.getText();
        double novoValor = Double.parseDouble(valor.getText());
        String novoCpfCliente = cliente.getText(); 
        int novoIdFunc = Integer.parseInt(funcionario.getText()); 
        int novoIdVeiculo = Integer.parseInt(veiculo.getText()); 
        
        Cliente novoObjCliente = controller.consultarCliente(novoCpfCliente);
        Funcionario novoObjFunc = controller.consultarFuncionario(novoIdFunc);
        Veiculo novoObjVeiculo = controller.consultarVeiculo(novoIdVeiculo); 

        if (novoObjCliente == null || novoObjFunc == null || novoObjVeiculo == null) {
            JOptionPane.showMessageDialog(this, "Erro: Cliente, Funcionário ou Veículo não encontrados!");
            return;
        }
        
        if (novoId == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Consulte uma venda antes de alterar.");
            return;
        }

        this.controller.alterarVenda(novoId, novaData, novoValor, novoObjCliente, novoObjFunc, novoObjVeiculo);
    
        javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
        limparActionPerformed(evt);
    }//GEN-LAST:event_alterarVendaActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        id.setText("");
        data.setText("");
        valor.setText("");
        cliente.setText("");
        funcionario.setText("");
        veiculo.setText("");
    
        alterarVenda.setEnabled(false);
        removerVenda.setEnabled(false);
    }//GEN-LAST:event_limparActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        this.relatorioVenda.setVisible(true);
    }//GEN-LAST:event_relatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarVenda;
    private javax.swing.JTextField cliente;
    private javax.swing.JButton consultarVenda;
    private javax.swing.JTextField data;
    private javax.swing.JTextField funcionario;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpar;
    private javax.swing.JButton relatorio;
    private javax.swing.JButton removerVenda;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField veiculo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
