/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Funcionario;

import controller.Concessionaria;
import model.Funcionario;
import javax.swing.JOptionPane;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */

public class EditFuncionario extends javax.swing.JFrame {

    private final Concessionaria controller;
    private final RelatorioFuncionario relatorioFuncionario;
    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form FormularioFuncionario
     */
    public EditFuncionario(Concessionaria controller, RelatorioFuncionario relatorioFuncionario, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.relatorioFuncionario = relatorioFuncionario;
        this.menuPrincipal = menuPrincipal;
        
        alterarFunc.setEnabled(false);
        removerFunc.setEnabled(false);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        consultarFunc = new javax.swing.JButton();
        cargaHoraria = new javax.swing.JTextField();
        removerFunc = new javax.swing.JButton();
        limpar = new javax.swing.JButton();
        relatorio = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        alterarFunc = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        numMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qualificacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        descricaoFuncao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(null);

        consultarFunc.setBackground(new java.awt.Color(0, 168, 89));
        consultarFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        consultarFunc.setForeground(new java.awt.Color(255, 255, 255));
        consultarFunc.setText("Consultar");
        consultarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(consultarFunc);
        consultarFunc.setBounds(160, 140, 90, 30);
        jPanel1.add(cargaHoraria);
        cargaHoraria.setBounds(300, 200, 220, 30);

        removerFunc.setBackground(new java.awt.Color(227, 6, 19));
        removerFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        removerFunc.setForeground(new java.awt.Color(255, 255, 255));
        removerFunc.setText("Remover");
        removerFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerFuncActionPerformed(evt);
            }
        });
        jPanel1.add(removerFunc);
        removerFunc.setBounds(320, 290, 90, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar);
        limpar.setBounds(80, 140, 72, 30);

        relatorio.setBackground(new java.awt.Color(45, 60, 80));
        relatorio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        relatorio.setForeground(new java.awt.Color(255, 255, 255));
        relatorio.setText("Relatório");
        relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioActionPerformed(evt);
            }
        });
        jPanel1.add(relatorio);
        relatorio.setBounds(120, 350, 90, 30);

        jLabel6.setBackground(new java.awt.Color(95, 118, 153));
        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 80, 37, 16);
        jPanel1.add(nome);
        nome.setBounds(300, 100, 220, 30);

        alterarFunc.setBackground(new java.awt.Color(108, 117, 125));
        alterarFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarFunc.setForeground(new java.awt.Color(255, 255, 255));
        alterarFunc.setText("Alterar");
        alterarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(alterarFunc);
        alterarFunc.setBounds(420, 290, 72, 30);

        voltar.setBackground(new java.awt.Color(45, 60, 80));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(20, 350, 90, 30);

        jLabel3.setForeground(new java.awt.Color(95, 118, 153));
        jLabel3.setText("Número da Matrícula");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 80, 170, 16);
        jPanel1.add(numMatricula);
        numMatricula.setBounds(80, 100, 170, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Qualificação");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(300, 230, 74, 16);
        jPanel1.add(qualificacao);
        qualificacao.setBounds(300, 250, 220, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("Descrição da Função");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 130, 220, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciar Funcionários");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 43);
        jPanel1.add(descricaoFuncao);
        descricaoFuncao.setBounds(300, 150, 220, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Carga horária semanal de trabalho");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(300, 180, 200, 16);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarFuncActionPerformed
        // TODO add your handling code here:
        try{ 
            int matriculaBusca = Integer.parseInt(numMatricula.getText());
        
            if (matriculaBusca <= 0) {
                JOptionPane.showMessageDialog(this, "Digite uma matrícula para buscar.");
                return;
            }
     
            Funcionario funcionario = this.controller.consultarFuncionario(matriculaBusca);
        
            if (funcionario != null) {
                nome.setText(funcionario.getNome());
                numMatricula.setText(String.valueOf(funcionario.getNumMatricula()));
                qualificacao.setText(funcionario.getQualificacao());
                descricaoFuncao.setText(funcionario.getDescricaoFuncao());
                cargaHoraria.setText(String.valueOf(funcionario.getCargaHorariaSemanal()));
            
                alterarFunc.setEnabled(true);  
                removerFunc.setEnabled(true); 
 
            } else {
                JOptionPane.showMessageDialog(this, "Funcionário não encontrado.");
                limparActionPerformed(evt);
            } 
        }catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite um número válido para a matrícula.");}
    }//GEN-LAST:event_consultarFuncActionPerformed

    private void removerFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerFuncActionPerformed
        // TODO add your handling code here:                                           
        try {
        String textoMatricula = numMatricula.getText();

        if (textoMatricula.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Digite a Matrícula para remover.");
            return;
        }

        int matricula = Integer.parseInt(textoMatricula);

        this.controller.removerFuncionario(matricula);
            
        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário removido com sucesso!");
        limparActionPerformed(evt); 
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "A matrícula deve ser um número válido!");
        }
    }//GEN-LAST:event_removerFuncActionPerformed

    private void alterarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFuncActionPerformed
        // TODO add your handling code here:
        try {
            int matricula = Integer.parseInt(numMatricula.getText());
            String novoNome = nome.getText();
            String novaQuali = qualificacao.getText();
            String novaDescricao = descricaoFuncao.getText();
            int novaCarga = Integer.parseInt(cargaHoraria.getText());

            if (novoNome.isEmpty()) {
                return;
            }
            
            this.controller.alterarFuncionario(matricula, novoNome, novaQuali, novaDescricao, novaCarga);

            javax.swing.JOptionPane.showMessageDialog(this, "Dados atualizados com sucesso!");
            limparActionPerformed(evt);
        
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: Matrícula e Carga Horária devem ser números válidos.");
        }
    }//GEN-LAST:event_alterarFuncActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltarActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        numMatricula.setText("");
        qualificacao.setText("");
        descricaoFuncao.setText("");
        cargaHoraria.setText("");
    
        alterarFunc.setEnabled(false);
        removerFunc.setEnabled(false);
 
    }//GEN-LAST:event_limparActionPerformed

    private void relatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioActionPerformed
        // TODO add your handling code here:
        this.relatorioFuncionario.setVisible(true);
    }//GEN-LAST:event_relatorioActionPerformed

;                      

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarFunc;
    private javax.swing.JTextField cargaHoraria;
    private javax.swing.JButton consultarFunc;
    private javax.swing.JTextField descricaoFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numMatricula;
    private javax.swing.JTextField qualificacao;
    private javax.swing.JButton relatorio;
    private javax.swing.JButton removerFunc;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
