/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Venda;

import controller.Concessionaria;
import model.Venda;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Funcionario;
import model.Veiculo;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */
public class FormularioVenda extends javax.swing.JFrame {

    private final Concessionaria controller;
    private final RelatorioVenda relatorioVenda;
    private EditVenda editVenda;
    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form FormularioVenda
     */
    
    public void setEditVenda(EditVenda editVenda) {
        this.editVenda = editVenda;
    }
    
    public FormularioVenda(Concessionaria controller, RelatorioVenda relatorioVenda, MenuPrincipal menuPrincipal, EditVenda editVenda) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.relatorioVenda = relatorioVenda;
        this.menuPrincipal = menuPrincipal;
        this.editVenda = editVenda;
        
        cadastrarVenda.setEnabled(true);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cadastrarVenda = new javax.swing.JButton();
        Gerenciamento = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        veiculo = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(519, 191, 0, 0);

        jPanel2.setBackground(new java.awt.Color(18, 18, 18));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gerenciamento de Vendas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 43);

        cadastrarVenda.setBackground(new java.awt.Color(0, 168, 89));
        cadastrarVenda.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarVenda.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarVenda.setText("Cadastrar ");
        cadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarVendaActionPerformed(evt);
            }
        });
        jPanel2.add(cadastrarVenda);
        cadastrarVenda.setBounds(290, 350, 120, 30);

        Gerenciamento.setBackground(new java.awt.Color(45, 60, 80));
        Gerenciamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        Gerenciamento.setText("Gerenciamento");
        Gerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoActionPerformed(evt);
            }
        });
        jPanel2.add(Gerenciamento);
        Gerenciamento.setBounds(20, 350, 120, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Data");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(170, 90, 170, 16);
        jPanel2.add(data);
        data.setBounds(170, 110, 260, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Valor");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(170, 290, 160, 16);
        jPanel2.add(valor);
        valor.setBounds(170, 310, 260, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("CPF Cliente");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 140, 180, 16);
        jPanel2.add(cliente);
        cliente.setBounds(170, 160, 260, 30);

        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("ID Funcionário");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 190, 100, 16);
        jPanel2.add(funcionario);
        funcionario.setBounds(170, 210, 260, 30);

        jLabel7.setForeground(new java.awt.Color(95, 118, 153));
        jLabel7.setText("ID Veículo");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(170, 240, 190, 16);
        jPanel2.add(veiculo);
        veiculo.setBounds(170, 260, 260, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel2.add(limpar);
        limpar.setBounds(202, 350, 80, 30);

        Voltar.setBackground(new java.awt.Color(45, 60, 80));
        Voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        jPanel2.add(Voltar);
        Voltar.setBounds(20, 310, 72, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVendaActionPerformed
        // TODO add your handling code here:
        try {

            String dataVenda = data.getText();
            double valorVenda = Double.parseDouble(valor.getText());
            String cpfCliente = cliente.getText(); 
            int idFunc = Integer.parseInt(funcionario.getText()); 
            int idVeiculo = Integer.parseInt(veiculo.getText()); 

            Cliente objCliente = controller.consultarCliente(cpfCliente);
            Funcionario objFunc = controller.consultarFuncionario(idFunc);
            Veiculo objVeiculo = controller.consultarVeiculo(idVeiculo); 

        if (objCliente == null || objFunc == null || objVeiculo == null) {
            JOptionPane.showMessageDialog(this, "Erro: Cliente, Funcionário ou Veículo não encontrados!");
            return;
        }

        this.controller.cadastrarVenda(dataVenda, valorVenda, objCliente, objFunc, objVeiculo);
        JOptionPane.showMessageDialog(this, "Venda realizada com sucesso!");
        limparActionPerformed(evt);

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Verifique se ID e Valor são números válidos.");
    }

        valor.setText("");
        cliente.setText("");
        funcionario.setText("");
        veiculo.setText("");
    }//GEN-LAST:event_cadastrarVendaActionPerformed

    private void GerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoActionPerformed
        // TODO add your handling code here:
        editVenda.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GerenciamentoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:

        data.setText("");
        valor.setText("");
        cliente.setText("");
        funcionario.setText("");
        veiculo.setText("");
    
        cadastrarVenda.setEnabled(true); 
    }//GEN-LAST:event_limparActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerenciamento;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton cadastrarVenda;
    private javax.swing.JTextField cliente;
    private javax.swing.JTextField data;
    private javax.swing.JTextField funcionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField valor;
    private javax.swing.JTextField veiculo;
    // End of variables declaration//GEN-END:variables
}
