/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Veiculo;

import controller.Concessionaria;
import model.Veiculo;
import javax.swing.JOptionPane;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */
public class FormularioVeiculo extends javax.swing.JFrame {
    
    private final Concessionaria controller;
    private MenuPrincipal menuPrincipal;
    private EditVeiculo editVeiculo;

    /**
     * Creates new form FormularioVeiculo
     */
    
    public void setEditVeiculo(EditVeiculo editVeiculo) {
        this.editVeiculo = editVeiculo;
    }
    
    public FormularioVeiculo(Concessionaria controller, MenuPrincipal menuPrincipal, EditVeiculo editVeiculo) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.editVeiculo = editVeiculo;
        this.menuPrincipal = menuPrincipal;
        
        cadastrarVeiculo.setEnabled(true);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cadastrarVeiculo = new javax.swing.JButton();
        Gerenciamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        numMarchas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        numPortas = new javax.swing.JTextField();
        Marca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        anoFabricacao = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Veículos");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 43);

        cadastrarVeiculo.setBackground(new java.awt.Color(0, 168, 89));
        cadastrarVeiculo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarVeiculo.setText("Cadastrar ");
        cadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarVeiculoActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarVeiculo);
        cadastrarVeiculo.setBounds(290, 350, 120, 30);

        Gerenciamento.setBackground(new java.awt.Color(45, 60, 80));
        Gerenciamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        Gerenciamento.setText("Gerenciamento");
        Gerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoActionPerformed(evt);
            }
        });
        jPanel1.add(Gerenciamento);
        Gerenciamento.setBounds(20, 350, 120, 30);

        jLabel3.setForeground(new java.awt.Color(95, 118, 153));
        jLabel3.setText("Modelo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 90, 180, 16);

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel1.add(nome);
        nome.setBounds(170, 110, 260, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Cor");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 190, 90, 16);
        jPanel1.add(cor);
        cor.setBounds(170, 210, 260, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Número de marchas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 140, 130, 16);
        jPanel1.add(numMarchas);
        numMarchas.setBounds(170, 160, 120, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("Número de portas");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 240, 150, 16);
        jPanel1.add(numPortas);
        numPortas.setBounds(170, 260, 260, 30);

        Marca.setForeground(new java.awt.Color(95, 118, 153));
        Marca.setText("Marca");
        jPanel1.add(Marca);
        Marca.setBounds(170, 290, 170, 16);
        jPanel1.add(marca);
        marca.setBounds(170, 310, 260, 30);

        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("Ano de fabricação");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 140, 130, 16);
        jPanel1.add(anoFabricacao);
        anoFabricacao.setBounds(302, 160, 130, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setLabel("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar);
        limpar.setBounds(202, 350, 80, 30);

        voltar1.setBackground(new java.awt.Color(45, 60, 80));
        voltar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar1.setForeground(new java.awt.Color(255, 255, 255));
        voltar1.setText("Voltar");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(voltar1);
        voltar1.setBounds(20, 310, 72, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarVeiculoActionPerformed
        // TODO add your handling code here:
        try{

            String nomeVeiculo = nome.getText();
            String corVeiculo = cor.getText();
            int numMarchaVeiculo = Integer.parseInt(numMarchas.getText());
            int numPortaVeiculo = Integer.parseInt(numPortas.getText());
            String marcaVeiculo = marca.getText();
            String anoFabricacaoVeiculo = anoFabricacao.getText();
            
            this.controller.cadastrarVeiculo(nomeVeiculo, corVeiculo, numMarchaVeiculo, numPortaVeiculo, marcaVeiculo, anoFabricacaoVeiculo);
            JOptionPane.showMessageDialog(this, "Veículo cadastrado com sucesso!");
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Id, Número de marchas e Número de portas devem ser números!");
        }
        
    
        nome.setText("");
        cor.setText("");
        numMarchas.setText("");
        numPortas.setText("");
        marca.setText("");
        anoFabricacao.setText("");
    }//GEN-LAST:event_cadastrarVeiculoActionPerformed

    private void GerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoActionPerformed
         // TODO add your handling code here:
        editVeiculo.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GerenciamentoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:

        nome.setText("");
        cor.setText("");
        numMarchas.setText("");
        numPortas.setText("");
        marca.setText("");
        anoFabricacao.setText("");
    
        cadastrarVeiculo.setEnabled(true); 
    }//GEN-LAST:event_limparActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerenciamento;
    private javax.swing.JLabel Marca;
    private javax.swing.JTextField anoFabricacao;
    private javax.swing.JButton cadastrarVeiculo;
    private javax.swing.JTextField cor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numMarchas;
    private javax.swing.JTextField numPortas;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
