/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Funcionario;

import controller.Concessionaria;
import model.Funcionario;
import javax.swing.JOptionPane;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */

public class FormularioFuncionario extends javax.swing.JFrame {

    private final Concessionaria controller;
    private MenuPrincipal menuPrincipal;
    private EditFuncionario editFuncionario;
    
    /**
     * Creates new form FormularioFuncionario
     */
    
    public void setEditFuncionario(EditFuncionario editFuncionario) {
        this.editFuncionario = editFuncionario;
    }
    
    public FormularioFuncionario(Concessionaria controller, EditFuncionario editFuncionario, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.menuPrincipal = menuPrincipal;
        this.editFuncionario = editFuncionario;
        
        cadastrarFunc.setEnabled(true);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        limparActionPerformed(null);
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cargaHoraria = new javax.swing.JTextField();
        limpar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        Gerenciamento = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        numMatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        qualificacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        descricaoFuncao = new javax.swing.JTextField();
        cadastrarFunc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setLayout(null);
        jPanel1.add(cargaHoraria);
        cargaHoraria.setBounds(170, 210, 260, 30);

        limpar.setBackground(new java.awt.Color(255, 153, 0));
        limpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        limpar.setForeground(new java.awt.Color(255, 255, 255));
        limpar.setText("Limpar");
        limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparActionPerformed(evt);
            }
        });
        jPanel1.add(limpar);
        limpar.setBounds(200, 350, 80, 30);

        jLabel6.setBackground(new java.awt.Color(95, 118, 153));
        jLabel6.setForeground(new java.awt.Color(95, 118, 153));
        jLabel6.setText("Nome");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 90, 250, 16);
        jPanel1.add(nome);
        nome.setBounds(170, 110, 260, 30);

        Gerenciamento.setBackground(new java.awt.Color(45, 60, 80));
        Gerenciamento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Gerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        Gerenciamento.setText("Gerenciamento");
        Gerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerenciamentoActionPerformed(evt);
            }
        });
        jPanel1.add(Gerenciamento);
        Gerenciamento.setBounds(20, 350, 120, 30);

        jLabel3.setForeground(new java.awt.Color(95, 118, 153));
        jLabel3.setText("Número da Matrícula");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(170, 290, 230, 16);
        jPanel1.add(numMatricula);
        numMatricula.setBounds(170, 310, 260, 30);

        jLabel4.setForeground(new java.awt.Color(95, 118, 153));
        jLabel4.setText("Qualificação");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 240, 230, 16);
        jPanel1.add(qualificacao);
        qualificacao.setBounds(170, 260, 260, 30);

        jLabel5.setForeground(new java.awt.Color(95, 118, 153));
        jLabel5.setText("Descrição da Função");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 140, 250, 16);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Funcionário");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 13, 600, 40);
        jPanel1.add(descricaoFuncao);
        descricaoFuncao.setBounds(170, 160, 260, 30);

        cadastrarFunc.setBackground(new java.awt.Color(0, 168, 89));
        cadastrarFunc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastrarFunc.setForeground(new java.awt.Color(255, 255, 255));
        cadastrarFunc.setText("Cadastrar ");
        cadastrarFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarFuncActionPerformed(evt);
            }
        });
        jPanel1.add(cadastrarFunc);
        cadastrarFunc.setBounds(290, 350, 120, 30);

        jLabel2.setForeground(new java.awt.Color(95, 118, 153));
        jLabel2.setText("Carga horária semanal de trabalho");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 190, 240, 16);

        voltar1.setBackground(new java.awt.Color(45, 60, 80));
        voltar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar1.setForeground(new java.awt.Color(255, 255, 255));
        voltar1.setText("Voltar");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });
        jPanel1.add(voltar1);
        voltar1.setBounds(20, 313, 72, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarFuncActionPerformed
        // TODO add your handling code here:
        try{
            String nomeFunc = nome.getText();
            int num = Integer.parseInt(numMatricula.getText());
            String quali = qualificacao.getText();
            String descricao = descricaoFuncao.getText();
            int carga = Integer.parseInt(cargaHoraria.getText());
            boolean sucesso = this.controller.cadastrarFuncionario(nomeFunc, num, quali, descricao, carga);
            
            if (sucesso) {
            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro: Matrícula já existente!", "Erro", JOptionPane.ERROR_MESSAGE);
            }
            
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Matrícula e Carga Horária devem ser números!");
        }
        
        nome.setText("");
        numMatricula.setText("");
        qualificacao.setText("");
        descricaoFuncao.setText("");
        cargaHoraria.setText("");
    }//GEN-LAST:event_cadastrarFuncActionPerformed

    private void GerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerenciamentoActionPerformed
        // TODO add your handling code here:
        editFuncionario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GerenciamentoActionPerformed

    private void limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparActionPerformed
        // TODO add your handling code here:
        nome.setText("");
        numMatricula.setText("");
        qualificacao.setText("");
        descricaoFuncao.setText("");
        cargaHoraria.setText("");
    
        cadastrarFunc.setEnabled(true); 
    }//GEN-LAST:event_limparActionPerformed

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltar1ActionPerformed
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltar1ActionPerformed

    /**
     * @param args the command line arguments
     */

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gerenciamento;
    private javax.swing.JButton cadastrarFunc;
    private javax.swing.JTextField cargaHoraria;
    private javax.swing.JTextField descricaoFuncao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpar;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numMatricula;
    private javax.swing.JTextField qualificacao;
    private javax.swing.JButton voltar1;
    // End of variables declaration//GEN-END:variables
}
