/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.Venda;

import controller.Concessionaria;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import view.MenuPrincipal;

/**
 *
 * @author hiago
 */
public class RelatorioVenda extends javax.swing.JFrame {

    private Concessionaria controller;
    private MenuPrincipal menuPrincipal;
    
    /**
     * Creates new form RelatorioVenda
     */
    public RelatorioVenda(Concessionaria controller, MenuPrincipal menuPrincipal) {
        initComponents();
        setLocationRelativeTo(null);
        
        this.controller = controller;
        this.menuPrincipal = menuPrincipal;
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Vendas");
        
        gerarRelatorio();
    }
    
    public void setMenuPrincipal(MenuPrincipal menuPrincipal) {
        this.menuPrincipal = menuPrincipal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        gerar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(616, 438));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(18, 18, 18));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanel1.setLayout(null);

        areaTexto.setBackground(new java.awt.Color(30, 30, 30));
        areaTexto.setColumns(20);
        areaTexto.setForeground(new java.awt.Color(255, 255, 255));
        areaTexto.setRows(5);
        jScrollPane1.setViewportView(areaTexto);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 88, 460, 240);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 236, 239));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatório de Vendas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 10, 600, 52);

        gerar.setBackground(new java.awt.Color(0, 168, 89));
        gerar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        gerar.setForeground(new java.awt.Color(255, 255, 255));
        gerar.setText("Gerar Relatório");
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });
        jPanel1.add(gerar);
        gerar.setBounds(150, 340, 120, 30);

        voltar.setBackground(new java.awt.Color(45, 60, 80));
        voltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        voltar.setForeground(new java.awt.Color(255, 255, 255));
        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        jPanel1.add(voltar);
        voltar.setBounds(70, 340, 72, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerarRelatorio() {
        String textoRelatorio = this.controller.getRelatorioVendas();
        
        areaTexto.setText(textoRelatorio);
    }
    
    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        // TODO add your handling code here:
        gerarRelatorio();
    }//GEN-LAST:event_gerarActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        // TODO add your handling code here:
        if (menuPrincipal != null) {
            menuPrincipal.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro: Menu principal não disponível");
        }
    }//GEN-LAST:event_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton gerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
